[config]
model = "ollama/llama3.2:1b"
fallback_models = ["ollama/llama3.2:1b"]
custom_model_max_tokens = 8192
duplicate_examples = true
custom_reasoning_model = true
git_provider = "local"

[ollama]
api_base = "http://localhost:11434"

[local]
# You can customize these paths if needed
# description_path = "path/to/description.md"
# review_path = "path/to/review.md"
